# Generated by Django 6.0.5 on 2026-05-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='feed_post_created_e5d35a_idx',
            old_name='feed_post_created_3d8f05_idx',
        ),
    ]
