# Generated by Django 6.0.5 on 2026-05-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roommessage_pomodorosession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pomodorosession',
            new_name='rooms_pomod_room_id_d43475_idx',
            old_name='rooms_pomodoro_room_id_1dd2ac_idx',
        ),
        migrations.RenameIndex(
            model_name='roommessage',
            new_name='rooms_roomm_room_id_9de674_idx',
            old_name='rooms_roommsg_room_id_78fb6e_idx',
        ),
    ]
